major change: dynamically derive EDID based on reported resolution
This introduces a subsystem where "on first boot" a function is called
that derives an EDID based upon the monitor that the NeTV is plugged into.

The program customize_edid reads the native EDID from the TV, compares
it against the resolutions supported in matchmoded_timings.h, and creates
an EDID based upon the intersection of the two.

The resulting EDID is written to /psp/cached.edid, where the netv_service
script checks if it exists and is valid, and if it is does not run the
program again.

This means every time you factory reset it'll have to regenerate the EDID.
That's a feature.

A call from the control panel to "automatically adjust settings" should
also be added. This call would simply invoke customize_edid, and everything
should work just like magic from there.

diff --git a/recipes/netv/helpers/netv_service b/recipes/netv/helpers/netv_service
--- a/recipes/netv/helpers/netv_service
+++ b/recipes/netv/helpers/netv_service
@@ -20,12 +20,31 @@ case "$1" in
 	      fpga_ctl H  # force HPD
 	      sleep 1  # this may be removeable, but just in case FPGA takes a moment to start...
 	      fpga_ctl H  # force HPD
-	      modeline /lib/firmware/1080p24_720p_480p.edid
+
 	      writecached_Km # write the cached Km in, if it exists
+
+	      # validate the EDID
+	      validate_edid /psp/cached.edid
+	      if [ [ $? != 0 ] ] # check return code
+	      then
+		  # generate an EDID if the cached edid is not valid
+		  customize_edid -f /psp/cached.edid
+		  if [ [ $? != 0 ] ]
+		  then # this case happens if for some reason derive_km was triggered
+		      echo "couldn't get semaphore, waiting 5 seconds and trying again"
+		      sleep 5 # sleep it off and run it again.
+		      customize_edid -f /psp/cached.edid
+		  fi
+
+		  modeline /psp/cached.edid
+	      else 
+		  modeline /psp/cached.edid
+	      fi
+
 	      fpga_ctl E  # force EDID squashing
 	      fpga_ctl h  # reconnect device
-	      # Km re-derivation is now called by an HPD event at this point
 
+	      # Km re-derivation is now called by an HPD event at this point
 	      echo "starting matchmode daemon"
 	      matchmoded
 
